name: authentication_repository
description: An Ozare flutter package which manages the authentication domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  cloud_firestore: ^4.4.4
  equatable: ^2.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  google_sign_in: ^6.0.2
  local_api:
    path: ../local_api
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.3.3
  firebase_auth_oauth_platform_interface: ^1.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^4.0.0
