name: ozare_repository
description: An Ozare package which manages remote data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+4
  json_annotation: ^4.8.0
  livescore_repository:
    path: ../livescore_repository
  path_provider: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
