// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7o5IcqvP1IV0z_vHXDFOdAKGAtIB5rCs',
    appId: '1:577898555257:web:b7851ae497b955a2b371a8',
    messagingSenderId: '577898555257',
    projectId: 'ozare-e8ed6',
    authDomain: 'ozare-e8ed6.firebaseapp.com',
    storageBucket: 'ozare-e8ed6.appspot.com',
    measurementId: 'G-DXXW2GQCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4X2QxkGacd5Bhah9_eLBf2D-Mfur7Jlo',
    appId: '1:577898555257:android:2adc18c12738e832b371a8',
    messagingSenderId: '577898555257',
    projectId: 'ozare-e8ed6',
    storageBucket: 'ozare-e8ed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2IE7ejIkmwEopOkMz97ie3oEJt1JKDVc',
    appId: '1:577898555257:ios:4bd2be1210f851f0b371a8',
    messagingSenderId: '577898555257',
    projectId: 'ozare-e8ed6',
    storageBucket: 'ozare-e8ed6.appspot.com',
    androidClientId: '577898555257-6obmfg1j38cqpit7lo9h9jptklqmfr94.apps.googleusercontent.com',
    iosClientId: '577898555257-gt8hh3aniii0u8v284l70iai69cvat76.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.ozare',
  );
}
